# Generated by Django 6.0.3 on 2026-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
