# Generated by Django 6.0.3 on 2026-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
